config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :courses
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # form to log the user in 
  get '/login', to: 'sessions#new'

  # log the user in 
  post '/sessions', to: 'sessions#create'

  # log out, make this post in real life but tests require get
  post '/logout', to: 'sessions#destroy'
  
  # atttendance 
  resources :attendances, only: [:index, :create, :update, :destroy]
  resources :courses, only: [:show] do
    resources :attendances, only: [:show, :index, :new, :edit]
  end

  # have an attendance resource for students 
  resources :users, only: [:show] do 
    resources :attendances, only: [:index]
  end 

  resources :user_courses, only: [:edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_courses 
    has_many :courses, through: :user_courses 
    has_many :attendance_entries 

    has_secure_password
    validates :name, presence: true 
    validates :name, uniqueness: true 

    # need validation code 
    attr_accessor :code
    # validates :name, uniqueness: {scope: :role,  message: " - A user with this name and role has already been created."} 

    include Schedulable::InstanceMethods

    def role?(role)
        self.role.downcase.include?(role)
    end 

    def course_list 
        self.courses.collect{|course| course.name}.join(', ')
    end 

    def self.all_users(role)
        self.all.select{|user| user.role?(role)}.sort_by{|u| u.name.downcase}
    end 

    def self.sort_by_name
        self.all.sort_by{|u| u.name.downcase}
    end 
    
    def get_schedule_hash()
        overlap = false  
        shash = {} 
        Course.sort_by_time(self.courses).each do |course| 
            ["Mon", "Tue", "Wed", "Thu", "Fri"].each do |day| 
                if course.scheduled_on?(day) 
                    if shash[course.time] and shash[course.time][day]
                        dlist = shash[course.time][day]
                        dlist << course 
                        overlap = true 
                    elsif shash[course.time]
                        thash = shash[course.time] 
                        thash[day] = [course]
                    else
                        shash[course.time] = {day => [course]}
                    end 
                end 
            end 
        end 
        [overlap, shash] 
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_login, only: [:index, :show, :edit, :update, :destroy]

    # 8/29/21 originally, but changed in line 8
    # before_action :require_admin, only: :index
    before_action :require_teacher, only: :index
    def index 
        if !params[:role].blank?
            flash[:alert] = params[:role]
            @users = User.where(role: params[:role])
        else 
            @users = User.all
        end
    end 

    before_action :admin_registration, only: :new
    def new 
        @user = User.new 
    end 

    before_action :protect_registration, only: [:create]
    def create 
        @user = User.new(user_params)
        if @user.save
            # Admins can create new users without needing to be logged in as the new user
            if logged_in? && current_user.role?('admin')
                redirect_to users_path, notice: "#{@user.name} [#{@user.role}] successfully created."
            else # Log them in 
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            end 
        else 
            render :new 
        end 
    end 

    def show 
        sinfo = @user.get_schedule_hash()
        overlap = sinfo[0]
        @shash = sinfo[1]
        if overlap
            flash.now.notice = 'Warning: There may be a scheduling conflict. Please check weekly schedule for overlapping class times.'
        end 
        if current_user != @user 
            redirect_to user_path(current_user), notice: 'Sorry, an Admin or Teacher role is required for access.' unless (current_user.role?('admin') or current_user.role?('teacher'))
        end 
    end 

    def edit 
        if current_user != @user 
            redirect_to user_path(current_user), notice: 'Sorry, an Admin role is required for access.' unless current_user.role?('admin')
        end 
    end 

    def update
        if @user.update(user_edit_params)
            redirect_to user_path(@user), notice: "Successfully updated user information for #{@user.name} [#{@user.role}]."
        else 
            render :edit 
        end  
    end 

    def destroy 
        # todo: logout if a user is deleting themselves (redirect depending on role)
        # if student or teacher, logout and redirect else users_path (admiN)
        # todo: redirect to root_path (unless admin, then redirect to users_path)
        @user.destroy
        # redirect_to users_path, notice: "#{@user.name} was successfully deleted."
        # binding.pry
        if current_user != @user
            redirect_to users_path, notice: "#{@user.name} was successfully deleted."
        else 
            redirect_to root_path, notice: "Your profile has been successfully deleted."
        end 
    end 

    private 

    def set_user 
        @user = User.find(params[:id])
    end 

    def user_params 
        params.require(:user).permit(:name, :password, :role, :code)
    end 

    def user_edit_params
        params.require(:user).permit(:name, :password)
    end 

    def validate_registration
        !!(params[:user][:code] == ENV['ADMIN_CODE'] && params[:user][:role] == 'Admin') || 
        (params[:user][:code] == ENV['TEACHER_CODE'] && params[:user][:role] == 'Teacher') || 
        (params[:user][:code] == ENV['STUDENT_CODE'] && params[:user][:role] == 'Student')
    end 

    def protect_registration
        if !validate_registration
            redirect_to new_user_path, notice: 'Sorry, the registration code is invalid for the role in which you are registering'
        end 
    end 

    def admin_registration
        if logged_in? && !current_user.role?('admin')
            redirect_to user_path(current_user), notice: 'Sorry, you must be an Admin to register a new user.'
        end
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin.html.erb
    <p>
        <%= link_to "Update Profile", edit_user_path(current_user) %>
    </p>
    <table>
        
            <tr>
                <th>Courses</th>
                <th>Users</th>
                <th>Attendance</th>
            </tr>
            <tr>
                <td><%= link_to "Manage Courses", courses_path %> <br> <%= link_to "Create Course", new_course_path %></td>
                <td><%= link_to "Manage Users", users_path %> <br> <%= link_to "Create User", new_user_path %> <br> <%= link_to "Most Courses", '/users/most_courses' %></td>
                <td><%= link_to "Manage Attendance", attendances_path %> <br> <%= link_to "Take Attendance", courses_path %></td>
            </tr>
    </table>

app/views/users/_form.html.erb
<div class="alert alert-info error_explanation">
  <%= flash[:notice] %>
</div>

<% if @user.errors.any? %>
  <div class="error_explanation">
    <h4>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this registration:
    </h4>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Enter Name Here", required: true %><br>

    <% if request.env['PATH_INFO'] == new_user_path %>
      <%= f.label :role %>
      <%= f.select(:role, ['Teacher', 'Admin', 'Student'])%><br>

      <%= f.label :code, "Registration Code"%>
      <%= f.text_field :code %><br>
    <% end %>

    <%= f.label :password %>
    <%= f.password_field :password, required: true %><br>

    <% if request.env['PATH_INFO'] == new_user_path %>
      <% if logged_in? && current_user.role?('admin') %>
        <%= f.submit %>
      <% else %>
        <%= f.submit "Sign Up"%>
      <% end %>
    <% else %>
      <%= f.submit "Update"%>
    <% end %>
<% end %>

app/views/users/_show.html.erb
<h2>Welcome, <%= current_user.name %>! [<%= current_user.role %>] </h2>

<div class="alert alert-info error_explanation">
  <%= flash[:notice] %>
</div>

<% if !current_user.role?('admin') || current_user != @user %>
    <% if current_user.role?('admin') %>
        <%= render 'admin' %>
        <br>
        <h2>Viewing <%= @user.name %>'s Homepage [<%= @user.role %>] </h2>
    <% end %>

    <% if current_user.role?('teacher') %>
        <h2>Viewing <%= @user.name %>'s Homepage [<%= @user.role %>] </h2>
    <% end %>
    
    <% if @user.role?('student') %>
        <p>
            <%= link_to 'View Attendance', user_attendances_path(@user) %> |
            <%= link_to "Update Profile", edit_user_path(@user) %> 
            <% if current_user.role?('admin') %>
                | <%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </p>
    <% end %>

    <% if @user.role?('teacher')%>
        <p>
            <%= link_to "Update Profile", edit_user_path(@user) %>
            <% if current_user.role?('admin') %>
                | <%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </p>
    <% end %>

    <div><form>
        <input type="button" value="Print Weekly Schedule" onClick="window.print()">
    </form></div><br>

    <h3>Today's Schedule (<%= @user.get_today %>):</h3>
    <table>
        <tr>
            <th>Time</th>
            <th>Course</th>
            <% if current_user.role?('teacher') %>
                <th>Attendance</th>
            <% end %>
        </tr>
        <% Course.sort_by_time(@user.todays_schedule).each do |course| %>
            <tr>
                <td><%= course.time %></td>
                <td><%= link_to course.name, course_path(course) %></td>
                <% if current_user.role?('teacher') %><td>
                    <%= link_to 'Take Attendance', new_course_attendance_path(course) %>
                </td><% end %>
            </tr>
        <% end %>
    </table>

    <br>
    <div class="print">
        <h3><%= @user.name %>'s Weekly Schedule:</h3>
        <table>
            <tr>
            <th>Time</th>
            <th>Mon</th>
            <th>Tue</th>
            <th>Wed</th>
            <th>Thu</th>
            <th>Fri</th>
            </tr>
        <% @shash.each do |time, dhash| %>
            <tr>
                <td><%= time %></td>
                <% ["Mon", "Tue", "Wed", "Thu", "Fri"].each do |day| %>
                    <% if dhash[day] %>
                        <td>
                        <% first = true %>
                        <% dhash[day].each do |course| %>
                            <% if !first %>
                                <br>
                            <% end %>
                            <%= link_to course.name, course_path(course) %> <br><%= course.location %>
                            <% first = false %>
                        <% end %>
                        </td>
                    <% else %>
                            <td></td>
                    <% end %>
                <% end %>
            </tr>
            <% end %>
        </table>
    </div>

    <br>
    <h3>Your Courses:</h3>
        <table>
            <tr>
                <th>Course Name</th>
                <th>Schedule</th>
                <th>Time</th>
                <th>Teachers</th>
                <% if @user.role?('student') %>
                    <th>Current Progress</th>
                <% end %>
                <% if current_user.role?('teacher') %>
                    <th>Enrollment</th>
                    <th>Options</th>
                <% end %>
            </tr>
            <% Course.sort_by_name(@user.courses).each do |course| %>
                <tr>
                    <td><%= link_to course.name, course_path(course) %></a></td>
                    <td><%= course.weekly_schedule %></td>
                    <td><%= course.time %></td>
                    <td><%= course.role_list('teacher') %></td>
                    <% if @user.role?('student') %>
                        <td><%= UserCourse.get_grade(@user, course.id)%></td>
                    <% end %>
                    <% if current_user.role?('teacher') %>
                        <td>(<%= course.get_users_count('student') %>/<%= course.capacity %> students)</td>
                        <td>
                            <%= link_to 'Edit', edit_course_path(course) %> | 
                            <%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' } %> |
                            <%= link_to 'Take Attendance', new_course_attendance_path(course) %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </table>
<% else %>
    <%= render 'admin' %>
<% end %>

app/views/users/edit.html.erb
<% if current_user === @user %> 
  <h2>Update Your Profile</h2>
<% else %> 
  <h2>Update <%= @user.name %>'s Profile</h2>
<% end %>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="print attendance">
<h2>All <%= flash[:alert] %> Users</h2>


<div class= "hideprint" >
    <div><form>
        <input type="button" value="Print Users List" onClick="window.print()">
    </form></div>

<div class="alert alert-info error_explanation">
  <%= flash[:notice] %>
  <% flash.clear %>
</div>

<p>
    <%= link_to "Create User", new_user_path %>
</p>

<div>
    <h3>Filter Users:</h3>
    <%= form_tag(users_path, method: 'get') do %>
         <!-- new code: filter by course -->
        <%= label_tag :role, "By Role" %>
        <%= select_tag :role, options_for_select(["Student", "Teacher", "Admin"]) %>
        <%= submit_tag "Filter" %>
    <% end %>
    <%= form_tag(users_path, method: 'get') do %>
        <%= submit_tag "Clear Filters" %>
    <% end %>
    <br>
</div>
</div>

<table>
    <tr>
        <th>Name</th>
        <th>Role</th>
        <th>Courses</th>
        <th>First Created</th>
        <th>Last Updated</th>
        <th>Attendance</th>
        <th>User Options</th>
    </tr>
    <% @users.sort_by{|u| u.name.downcase}.each do |user| %>
        <tr>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= user.role %></td>
            <td><%= user.course_list %></td>
            <td><%= first_created(user) %></td>
            <td><%= last_updated(user) %></td>
            <td>
                <% if user.role?('student') %>
                    <%= link_to 'View', user_attendances_path(user) %>
                <% end %>
            </td>
            <td>
                <%= link_to 'Edit', edit_user_path(user) %> | 
                <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %>
</table>
</div>

app/views/users/most_courses.html.erb
<h2>User with Most Courses</h2>
<%= User.most_courses.name %>

app/views/users/new.html.erb
<% if !logged_in? %>
    <h2>Sign Up</h2>
<% else %>
    <h2>Register a New User</h2>
<% end %>

<%= render 'form' %>

  <br>
  <% if !logged_in? && request.env['PATH_INFO'] == new_user_path %>
      <p>Already have an account? <%= link_to "Log In", root_path %></p>
  <% end %>

app/views/users/show.html.erb
<%= render 'show' %>