config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :courses
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # form to log the user in 
  get '/login', to: 'sessions#new'

  # log the user in 
  post '/sessions', to: 'sessions#create'

  # log out, make this post in real life but tests require get
  post '/logout', to: 'sessions#destroy'
  
  # atttendance 
  resources :attendances, only: [:index, :create, :update, :destroy]
  resources :courses, only: [:show] do
    resources :attendances, only: [:show, :index, :new, :edit]
  end

  # have an attendance resource for students 
  resources :users, only: [:show] do 
    resources :attendances, only: [:index]
  end 

  resources :user_courses, only: [:edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title>CourseClicker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>
  <body>
    <div class="wrapper">
      <div class="header">
        <h1>Course Clicker</h1>
      </div>
      <table>
        <% if !logged_in? %>

        <% elsif current_user.role?('admin') %>
          <th><%= link_to "Courses", courses_path %></th>
          <th><%= link_to "Users", users_path %></th>
          <th><%= link_to "Attendance", attendances_path %></th>
          <th><%= link_to "Home", user_path(current_user) %></th>
          <th><%= render 'sessions/logout' %></th>
        <% elsif current_user.role?('teacher') %>
          <th><%= link_to "Courses", courses_path %></th>
          <th><%= link_to "Users", users_path %></th>
          <th><%= link_to "Create Course", new_course_path %></th>
          <th><%= link_to "Attendance", attendances_path %></th>
          <th><%= link_to "Home", user_path(current_user) %></th>
          <th><%= render 'sessions/logout' %></th>
        <% elsif current_user.role?('student') %>
          <th><%= link_to "Courses", courses_path %></th>
          <th><%= link_to "Home", user_path(current_user) %></th>
          <th><%= render 'sessions/logout' %></th>
        <% end %>
      </table>

        <%= yield %>

      <footer class="branding">
        <small> 2020 <strong>CourseClicker</strong></small>
      </footer>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>